#
# NTU SC2006 Notes
# Mkdocs Config
#

site_name: NTU SC2006 Notes
site_description: NTU SC2006 Software Engineering Notes
site_author: SC2006 Docs Team
repo_url: https://github.com/mrzzy/ntu-sc2006-notes
theme:
  name: material
plugins:
  - search
  - with-pdf:
      cover_subtitle: NTU SC2006 Software Engineering Notes
      copyright: "&copy; SC2006 Docs Team"
  - kroki:
      FencePrefix: ""
      FileTypeOverrides:
        mermaid: png
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
