#
# NTU SC2006 Notes
# CI Pipeline
#

name: Lint & Build Notes

on:
  push: {}
jobs:
  lint:
    name: Lint Notes
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.13
          cache: "pip" # caching pip dependencies

      - name: Install Pip Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Lint Checks
        run: make lint

  build-pdf:
    name: Build Notes PDF
    runs-on: ubuntu-22.04
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.13
          cache: "pip" # caching pip dependencies

      - name: Install Pip Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Notes PDF
        run: make build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/pdf/document.pdf

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
